# 2022년 1월의 도서 판매 데이터를 기준으로,
# 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여,
# 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력
# 결과는 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 정렬
WITH TARGET AS (
    SELECT
        BOOK_ID,
        SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01'
        AND SALES_DATE < '2022-02-01'
    GROUP BY BOOK_ID
)
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(TG.SALES * B.PRICE) AS TOTAL_SALES
FROM TARGET AS TG
JOIN BOOK AS B
    ON TG.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;
