# 우유와 요거트를 동시에 구입한 장바구니의 아이디를 조회
# 결과는 장바구니의 아이디 순
WITH CART_MILK AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
),
CART_YOGURT AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)
SELECT M.CART_ID
FROM CART_MILK AS M
JOIN CART_YOGURT AS Y
    ON M.CART_ID = Y.CART_ID
ORDER BY M.CART_ID;