# 3세대의 대장균의 ID(ID) 를 출력
# 결과는 대장균의 ID 에 대해 오름차순 정렬
SELECT G3.ID
FROM ECOLI_DATA G1
JOIN ECOLI_DATA G2 ON G2.PARENT_ID = G1.ID
JOIN ECOLI_DATA G3 ON G3.PARENT_ID = G2.ID
WHERE G1.PARENT_ID IS NULL
ORDER BY G3.ID;
