# 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
# 결과는 총매출을 기준으로 내림차순 정렬해주시고,
# 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬
SELECT
    PI.PRODUCT_ID,
    PI.PRODUCT_NAME,
    TG.TOTAL_AMOUNT * PI.PRICE AS TOTAL_SALES
FROM (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) TG JOIN FOOD_PRODUCT AS PI
    ON TG.PRODUCT_ID = PI.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PI.PRODUCT_ID ASC;