# 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회
WITH TEMP AS (
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY
    UNION
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
)
SELECT
    FLAVOR
FROM TEMP
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;