# 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로
# 상위 3개의 맛을 조회
SELECT FH.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
) FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) JL ON FH.FLAVOR = JL.FLAVOR
ORDER BY (
    FH.TOTAL_ORDER + JL.TOTAL_ORDER
) DESC
LIMIT 3;