# 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 
# 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
# 결과는 카테고리명을 기준으로 오름차순 정렬
SELECT
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S
    ON S.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE >= DATE('2022-01-01')
    AND SALES_DATE < DATE('2022-02-01')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;