# 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
# 결과는 총거래금액을 기준으로 오름차순 정렬
SELECT
    U.USER_ID,
    U.NICKNAME,
    DONE_OVER_70.TOTAL_SALES
FROM (
    SELECT
        WRITER_ID AS USER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) DONE_OVER_70
JOIN USED_GOODS_USER U
    ON DONE_OVER_70.USER_ID = U.USER_ID
ORDER BY TOTAL_SALES ASC;